import Link from "next/link";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ToastContainer from "./components/Toast";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html key="layoutkey" lang="en">
      <body className={inter.className}>
        <ToastContainer/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
