import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html key="layoutkey" lang="en">
      <body className={inter.className}>
        <div className="w-full bg-slate-300">
          <nav className="w-full items-center flex justify-between max-w-5xl mx-auto h-[10vh] ">
            <Link href="/">App</Link>
            <Link href="/blogs/123">Blogs</Link>
          </nav>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
